Zadanie 10 - numpy

In [2]:
import numpy as np

In [ ]:
exams = np.array([
[78, 85, 92, 88],
[65, 72, 68, 70],
[90, 88, 95, 92],
[55, 60, 58, 62],
[82, 79, 85, 80]
])


bonus = np.array([5, 10, 5, 10])
multipliers = np.array([1.0, 1.1, 0.95, 1.15, 1.0])

exams_with_bonus = exams + bonus
exams_with_bonus

array([[ 83,  95,  97,  98],
       [ 70,  82,  73,  80],
       [ 95,  98, 100, 102],
       [ 60,  70,  63,  72],
       [ 87,  89,  90,  90]])

In [ ]:
finals_scores = exams_with_bonus * multipliers[:, np.newaxis]
finals_scores

array([[83.  , 95.  , 97.  , 98.  ],
       [77.  , 90.2 , 80.3 , 88.  ],
       [90.25, 93.1 , 95.  , 96.9 ],
       [69.  , 80.5 , 72.45, 82.8 ],
       [87.  , 89.  , 90.  , 90.  ]])

Zadanie 12 - numpy

In [ ]:
point_a = np.array([1, 2, 3, 4, 5])
point_b = np.array([5, 4, 3, 2, 1])
points = np.random.rand(4, 5)
def euclidean_distance(a, b):
    return round(np.sqrt(np.sum((a - b) ** 2)),2)    
distance_ab = euclidean_distance(point_a, point_b)
distance_ab

np.float64(6.324555320336759)

In [18]:
distance_matrix = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        distance_matrix[i, j] = euclidean_distance(points[i], points[j])
distance_matrix

array([[0.        , 0.611546  , 0.57277847, 0.54596945],
       [0.611546  , 0.        , 0.35398875, 0.87287081],
       [0.57277847, 0.35398875, 0.        , 0.7413867 ],
       [0.54596945, 0.87287081, 0.7413867 , 0.        ]])

Zadanie 7 - pandas

In [20]:
import pandas as pd

In [21]:
titanic = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
sorted_by_age = titanic.dropna(subset=['Age']).sort_values(by='Age')
youngest_10 = sorted_by_age.head(10)
oldest_10 = sorted_by_age.tail(10)
youngest_10

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S

In [26]:
oldest_10

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S

Zadanie 9 - pandas

In [31]:
chunk_size = 100
age_means = []
for i, chunk in enumerate(pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv", chunksize=chunk_size)):
    mean_age = chunk['Age'].mean()
    age_means.append(mean_age)
    print(f"Batch {i+1}: Mean Age = {mean_age}")    
global_mean = round(sum(age_means) / len(age_means),2)
print(f"Global Mean Age = {global_mean}")

global_mean_no_chunks = round(titanic['Age'].mean(), 2)
print(f"Global Mean Age without chunks = {global_mean_no_chunks}")

Batch 1: Mean Age = 27.46576923076923
Batch 2: Mean Age = 28.549382716049383
Batch 3: Mean Age = 30.753012048192772
Batch 4: Mean Age = 27.85525
Batch 5: Mean Age = 31.417763157894736
Batch 6: Mean Age = 32.80921052631579
Batch 7: Mean Age = 31.558641975308642
Batch 8: Mean Age = 28.715487804878048
Batch 9: Mean Age = 28.275974025974026
Global Mean Age = 29.71
Global Mean Age without chunks = 29.7